### ISSUE TITLE
ActiveRecord::UnknownAttributeError: unknown attribute: entity

### ISSUE THREAD

**Issue by anmolarora** [razorpay/razorpay-ruby#23]
```
from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:50:in `rescue in _assign_attribute'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:45:in `_assign_attribute'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:32:in `block in assign_attributes'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:26:in `each'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/attribute_assignment.rb:26:in `assign_attributes'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/core.rb:453:in `init_attributes'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/core.rb:196:in `initialize'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.8/lib/active_record/inheritance.rb:30:in `new'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/razorpay-1.2.1/lib/razorpay/request.rb:73:in `create_instance'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/razorpay-1.2.1/lib/razorpay/request.rb:48:in `request'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/razorpay-1.2.1/lib/razorpay/request.rb:30:in `all'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/razorpay-1.2.1/lib/razorpay/order.rb:21:in `all'
	from (irb):1
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/railties-4.1.8/lib/rails/commands/console.rb:90:in `start'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/railties-4.1.8/lib/rails/commands/console.rb:9:in `start'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/railties-4.1.8/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/ubuntu/.rvm/gems/ruby-2.3.0/gems/railties-4.1.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in](url)
```

**Comment by captn3m0** [comment]
Is the application source available somewhere? Active Record should not be getting called from the razorpay gem.

**Comment by anmolarora** [comment]
No, it's not available anywhere. I'm able to capture payments without any error. 
I'm trying to fetch all payments using below code then I'm getting the above-mentioned error.

> Razorpay::Payment.all

What could be the possible scenario which is causing this error?

**Comment by captn3m0** [comment]
Does it happen on every `.all` call? Because the stacktrace shows `Order.all` being called.

**Comment by anmolarora** [comment]
Yes @captn3m0, It's happening for all `.all` calls.

**Comment by anmolarora** [comment]
@captn3m0 Did you get any clue what might be happening that I'm getting this error?

**Comment by captn3m0** [comment]
No. My guess is that ActiveRecord might be overriding something on Object, and we should ideally work around that. We've made some changes in this regard on #25. 

Would it be possible to try out the current master?

Otherwise, I'm planning to setup a new test project with activerecord, but that might take some time.

**Comment by anmolarora** [comment]
Ok, @captn3m0. I'll try out the master and let you know if my problem is solved.

**Comment by anmolarora** [comment]
@captn3m0 So, I tried the current master and it's working fine in development. Is current master safe for  using in production?

**Comment by captn3m0** [comment]
Yes, it is. We have one minor development concern (involves upgrading a test env dependency) that we need to get through before making a new release.

Once that release is out, I'll update on this thread and you can shift to that instead.
