### ISSUE TITLE
[Discussion] Subscription Create with addons fails and the solution

### ISSUE THREAD

**Issue by pikender** [razorpay/razorpay-ruby#50]
**Subscription create with upfront fees as addons fails** 

## Scenario

* Subscription Api allows sending addons while creating subscriptions as a way to charge upfront fees
* When addons are passed with subscriptions, it fails with error `The item id field is required when item is not present.`. In the api request params, it can be seen that addon attributes are passed as desired.
* When custom headers are set to use `application/json` and data passed as json, it works.

## Discussion

* httparty sends data in `application/x-www-form-urlencoded` format by default which seems to be supported and working as expected by Razorpay apis but breaks in this particular case.
* Should we change the default as `application/json` and configure httparty to parse params in json when received ?
* Should we patch [Razorpay::Request#raw_request](https://github.com/razorpay/razorpay-ruby/blob/master/lib/razorpay/request.rb#L61) to support both and convert data to json based on `Content-Type` ?

    ```
    def raw_request(method, url, data = {})
      case method
      when :get
        @options[:query] = data
      when :post, :put, :patch
        if(@options[:headers].fetch('Content-Type', "") == "application/json")
          @options[:body] = data.to_json
        else
          @options[:body] = data
        end
      end

      self.class.send(method, url, @options)
    end
    ```
* Can we fix this in Razorpay Api's so that behavior remains same throughout whether using `Content-Type` as `application/json` or `application/x-www-form-urlencoded` ?

## API Log

```
2.3.3 :002 > addon_attrs = {:item=>{:name=>"fake_addon_name", :description=>"fake_addon_description", :currency=>"INR", :amount=>5000}, :quantity=>1}
 => {:item=>{:name=>"fake_addon_name", :description=>"fake_addon_description", :currency=>"INR", :amount=>5000}, :quantity=>1} 

2.3.3 :003 > s_attrs = { plan_id: 'plan_97l6xBrTEsPTXe', customer_id: 'cust_8jv29tdSNEpQj5', start_at: (Time.now + (60*60)).to_i, total_count: 3}
 => {:plan_id=>"plan_97l6xBrTEsPTXe", :customer_id=>"cust_8jv29tdSNEpQj5", :start_at=>1512068870, :total_count=>3} 

2.3.3 :004 > s = Razorpay::Subscription.create(s_attrs.merge(addons: [addon_attrs]))
opening connection to api.razorpay.com:443...
opened
starting SSL for api.razorpay.com:443...
SSL established
<- "POST /v1/subscriptions HTTP/1.1\r\nUser-Agent: Razorpay-Ruby/2.1.0\r\nAuthorization: Basic xxxxx\r\nConnection: close\r\nHost: api.razorpay.com\r\nContent-Length: 259\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n"
<- "plan_id=plan_97l6xBrTEsPTXe&customer_id=cust_8jv29tdSNEpQj5&start_at=1512068870&total_count=3&addons[][quantity]=1&addons[][item][name]=fake_addon_name&addons[][item][description]=fake_addon_description&addons[][item][currency]=INR&addons[][item][amount]=5000"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Cache-Control: max-age=0, must-revalidate, no-store, nocache, private\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Thu, 30 Nov 2017 18:07:56 GMT\r\n"
-> "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
-> "Pragma: no-cache\r\n"
-> "Server: Apache\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "Content-Length: 128\r\n"
-> "Connection: Close\r\n"
-> "\r\n"
reading 128 bytes...
-> "{\"error\":{\"code\":\"BAD_REQUEST_ERROR\",\"description\":\"The item id field is required when item is not present.\",\"field\":\"item_id\"}}"
read 128 bytes
Conn close
Razorpay::BadRequestError: The item id field is required when item is not present.
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:108:in `raise_error'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:85:in `create_instance'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:59:in `request'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:55:in `create'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/subscription.rb:13:in `create'
	from (irb):4
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli/console.rb:18:in `run'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:391:in `console'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `load'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `<main>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Subscription create with upfront fees as addons `still fails` when `Content-Type set` as `application/json`**

```
2.3.3 :005 > Razorpay.headers = { "Content-Type" => "application/json", "Accept" => "application/json" }
 => {"Content-Type"=>"application/json", "Accept"=>"application/json"} 

2.3.3 :006 > s = Razorpay::Subscription.create(s_attrs.merge(addons: [addon_attrs]))
opening connection to api.razorpay.com:443...
opened
starting SSL for api.razorpay.com:443...
SSL established
<- "POST /v1/subscriptions HTTP/1.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nUser-Agent: Razorpay-Ruby/2.1.0\r\nAuthorization: Basic xxxxx\r\nConnection: close\r\nHost: api.razorpay.com\r\nContent-Length: 259\r\n\r\n"
<- "plan_id=plan_97l6xBrTEsPTXe&customer_id=cust_8jv29tdSNEpQj5&start_at=1512068870&total_count=3&addons[][quantity]=1&addons[][item][name]=fake_addon_name&addons[][item][description]=fake_addon_description&addons[][item][currency]=INR&addons[][item][amount]=5000"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Cache-Control: max-age=0, must-revalidate, no-store, nocache, private\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Thu, 30 Nov 2017 18:09:06 GMT\r\n"
-> "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
-> "Pragma: no-cache\r\n"
-> "Server: Apache\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "Content-Length: 103\r\n"
-> "Connection: Close\r\n"
-> "\r\n"
reading 103 bytes...
-> "{\"error\":{\"code\":\"BAD_REQUEST_ERROR\",\"description\":\"The plan id field is required.\",\"field\":\"plan_id\"}}"
read 103 bytes
Conn close
Razorpay::BadRequestError: The plan id field is required.
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:108:in `raise_error'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:85:in `create_instance'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:59:in `request'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/request.rb:55:in `create'
	from /home/pikender/rails/vibrantstack/razorpay-ruby/lib/razorpay/subscription.rb:13:in `create'
	from (irb):6
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli/console.rb:18:in `run'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:391:in `console'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /home/pikender/.rvm/gems/ruby-2.3.3/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `load'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/bundle:23:in `<main>'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/pikender/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Subscription create with upfront fees as addons `passes` when `Content-Type` set as `application/json` and `data converted to json`**

```
2.3.3 :007 > s = Razorpay::Subscription.create(s_attrs.merge(addons: [addon_attrs]).to_json)
opening connection to api.razorpay.com:443...
opened
starting SSL for api.razorpay.com:443...
SSL established
<- "POST /v1/subscriptions HTTP/1.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nUser-Agent: Razorpay-Ruby/2.1.0\r\nAuthorization: Basic xxxxx\r\nConnection: close\r\nHost: api.razorpay.com\r\nContent-Length: 237\r\n\r\n"
<- "{\"plan_id\":\"plan_97l6xBrTEsPTXe\",\"customer_id\":\"cust_8jv29tdSNEpQj5\",\"start_at\":1512068870,\"total_count\":3,\"addons\":[{\"item\":{\"name\":\"fake_addon_name\",\"description\":\"fake_addon_description\",\"currency\":\"INR\",\"amount\":5000},\"quantity\":1}]}"
-> "HTTP/1.1 200 OK\r\n"
-> "Cache-Control: max-age=0, must-revalidate, no-store, nocache, private\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Thu, 30 Nov 2017 18:09:12 GMT\r\n"
-> "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
-> "Pragma: no-cache\r\n"
-> "Server: Apache\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "Content-Length: 379\r\n"
-> "Connection: Close\r\n"
-> "\r\n"
reading 379 bytes...
-> "{\"id\":\"sub_97lvgp0x2kyAEZ\",\"entity\":\"subscription\",\"plan_id\":\"plan_97l6xBrTEsPTXe\",\"customer_id\":\"cust_8jv29tdSNEpQj5\",\"status\":\"created\",\"current_start\":null,\"current_end\":null,\"ended_at\":null,\"quantity\":1,\"notes\":[],\"charge_at\":1512068870,\"start_at\":1512068870,\"end_at\":1517423400,\"auth_attempts\":0,\"total_count\":3,\"paid_count\":0,\"customer_notify\":true,\"created_at\":1512065352}"
read 379 bytes
Conn close
 => #<Razorpay::Subscription:0x00000001dec5a0 @attributes={"id"=>"sub_97lvgp0x2kyAEZ", "entity"=>"subscription", "plan_id"=>"plan_97l6xBrTEsPTXe", "customer_id"=>"cust_8jv29tdSNEpQj5", "status"=>"created", "current_start"=>nil, "current_end"=>nil, "ended_at"=>nil, "quantity"=>1, "notes"=>[], "charge_at"=>1512068870, "start_at"=>1512068870, "end_at"=>1517423400, "auth_attempts"=>0, "total_count"=>3, "paid_count"=>0, "customer_notify"=>true, "created_at"=>1512065352}> 

2.3.3 :008 > s = Razorpay::Subscription.fetch('sub_97lvgp0x2kyAEZ')
opening connection to api.razorpay.com:443...
opened
starting SSL for api.razorpay.com:443...
SSL established
<- "GET /v1/subscriptions/sub_97lvgp0x2kyAEZ? HTTP/1.1\r\nContent-Type: application/json\r\nAccept: application/json\r\nUser-Agent: Razorpay-Ruby/2.1.0\r\nAuthorization: Basic xxxxx\r\nConnection: close\r\nHost: api.razorpay.com\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Cache-Control: max-age=0, must-revalidate, no-store, nocache, private\r\n"
-> "Content-Type: application/json\r\n"
-> "Date: Thu, 30 Nov 2017 18:14:03 GMT\r\n"
-> "Expires: Fri, 01 Jan 1990 00:00:00 GMT\r\n"
-> "Pragma: no-cache\r\n"
-> "Server: Apache\r\n"
-> "Strict-Transport-Security: max-age=63072000; includeSubDomains\r\n"
-> "X-Frame-Options: SAMEORIGIN\r\n"
-> "Content-Length: 379\r\n"
-> "Connection: Close\r\n"
-> "\r\n"
reading 379 bytes...
-> "{\"id\":\"sub_97lvgp0x2kyAEZ\",\"entity\":\"subscription\",\"plan_id\":\"plan_97l6xBrTEsPTXe\",\"customer_id\":\"cust_8jv29tdSNEpQj5\",\"status\":\"created\",\"current_start\":null,\"current_end\":null,\"ended_at\":null,\"quantity\":1,\"notes\":[],\"charge_at\":1512068870,\"start_at\":1512068870,\"end_at\":1517423400,\"auth_attempts\":0,\"total_count\":3,\"paid_count\":0,\"customer_notify\":true,\"created_at\":1512065352}"
read 379 bytes
Conn close
 => #<Razorpay::Subscription:0x00000001d489f0 @attributes={"id"=>"sub_97lvgp0x2kyAEZ", "entity"=>"subscription", "plan_id"=>"plan_97l6xBrTEsPTXe", "customer_id"=>"cust_8jv29tdSNEpQj5", "status"=>"created", "current_start"=>nil, "current_end"=>nil, "ended_at"=>nil, "quantity"=>1, "notes"=>[], "charge_at"=>1512068870, "start_at"=>1512068870, "end_at"=>1517423400, "auth_attempts"=>0, "total_count"=>3, "paid_count"=>0, "customer_notify"=>true, "created_at"=>1512065352}> 
```

**Comment by pikender** [comment]
@captn3m0 @StSarc any feedback here ?

is there any consideration of changing it in _Razorpay Apis_ ?

**Comment by tessie** [comment]
@pikender  That is a really valid feedback. Thank you for pointing the issue. I think

-  we should override httparty default behavior and set content type as json and configure  params as json
